# Generated by Django 4.0.1 on 2023-02-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('die_punch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_of', models.CharField(blank=True, default='', max_length=255)),
                ('contact_no', models.BigIntegerField(blank=True, default=0, unique=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('designtion', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('place', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='die_punch.customerdetail')),
            ],
            options={
                'db_table': 'client_details',
            },
        ),
        migrations.CreateModel(
            name='MarketingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('month', models.CharField(blank=True, default='', max_length=100)),
                ('enquiry_received_by', models.CharField(blank=True, default='', max_length=100)),
                ('enquiry_mode', models.CharField(blank=True, default='', max_length=100)),
                ('quotation_ref_no', models.CharField(blank=True, default='', max_length=100)),
                ('quotation_given_by', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('quotation_mode', models.CharField(blank=True, default='', max_length=100)),
                ('quotation_remark', models.CharField(blank=True, default='', max_length=100)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('done_by', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('po_number', models.CharField(blank=True, default='', max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('po_received_on', models.DateField(blank=True, null=True)),
                ('po_mode', models.CharField(blank=True, default='', max_length=100)),
                ('po_amount', models.BigIntegerField(blank=True, default=0)),
                ('po_others', models.CharField(blank=True, default='', max_length=100)),
                ('po_tax', models.FloatField(blank=True, default=0.0)),
                ('po_total_amount', models.FloatField(blank=True, default=0.0)),
                ('po_amount_recieved', models.FloatField(blank=True, default=0.0)),
                ('po_balance_amount', models.FloatField(blank=True, default=0.0)),
                ('po_payment_terms', models.CharField(blank=True, default='', max_length=100)),
                ('po_payment_recieved_on', models.DateField(blank=True, null=True)),
                ('po_payment_details', models.CharField(blank=True, default='', max_length=100)),
                ('po_payment_details_mode', models.CharField(blank=True, default='', max_length=100)),
                ('po_account', models.CharField(blank=True, default='', max_length=100)),
                ('po_material_to_be_dispatched_by', models.CharField(blank=True, default='', max_length=100)),
                ('po_bill_no', models.CharField(blank=True, default='', max_length=100)),
                ('po_bill_date', models.DateField(blank=True, null=True)),
                ('dispatch_material_dispatched_on', models.DateField(blank=True, null=True)),
                ('dispatch_done_by', models.CharField(blank=True, default='', max_length=100)),
                ('dispatch_courier_details', models.CharField(blank=True, default='', max_length=100)),
                ('dispatch_destination', models.CharField(blank=True, default='', max_length=100)),
                ('form_creation_date', models.DateTimeField(auto_now_add=True)),
                ('form_modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='die_punch.customerdetail')),
                ('client_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.clientdetails')),
            ],
            options={
                'db_table': 'marketing_form',
            },
        ),
    ]
