# Generated by Django 4.0.1 on 2023-02-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_rename_done_by_status_marketingform_done_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingform',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.clientdetails'),
        ),
    ]
