# Generated by Django 4.0.1 on 2023-02-27 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BodyTipMachining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(blank=True, max_length=100, null=True)),
                ('customerMobile', models.CharField(blank=True, max_length=20, null=True)),
                ('customerEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('customerCompanyName', models.CharField(blank=True, max_length=200, null=True)),
                ('customerCompanyAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('customerCompanyCity', models.CharField(blank=True, max_length=50, null=True)),
                ('customerCompanyState', models.CharField(blank=True, max_length=50, null=True)),
                ('customerCompanyPincode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customerdetail',
            },
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DieBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DispachMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HardChrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HeadMachining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KeywayTaperFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='L1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='L2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Moc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackingDispach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.CharField(blank=True, max_length=50, null=True)),
                ('orderNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('order_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('dwgNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('drgDate', models.CharField(blank=True, max_length=50, null=True)),
                ('approvalDate', models.CharField(blank=True, max_length=50, null=True)),
                ('master', models.CharField(blank=True, max_length=50, null=True)),
                ('masterOut', models.CharField(blank=True, max_length=50, null=True)),
                ('masterIn', models.CharField(blank=True, max_length=50, null=True)),
                ('hitDate', models.CharField(blank=True, max_length=50, null=True)),
                ('estimatedDelivery', models.CharField(blank=True, max_length=50, null=True)),
                ('planningOut', models.CharField(blank=True, max_length=50, null=True)),
                ('planningIn', models.CharField(blank=True, max_length=50, null=True)),
                ('actualDelivery', models.CharField(blank=True, max_length=50, null=True)),
                ('couriesNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('user_1_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('user_2_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('user_3_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('user_admin_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('blank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.blank')),
                ('bodyTipMachining', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.bodytipmachining')),
                ('clientName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.customerdetail')),
                ('d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.d')),
                ('dieBlankUsed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.dieblank')),
                ('dispachMode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.dispachmode')),
                ('grinding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.grinding')),
                ('hardChrome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.hardchrome')),
                ('headMachining', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.headmachining')),
                ('ht', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.ht')),
                ('keywayTaperFinish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.keywaytaperfinish')),
                ('l1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.l1')),
                ('l2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.l2')),
                ('moc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.moc')),
                ('packingDispach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.packingdispach')),
                ('platingType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.platingtype')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.process')),
            ],
            options={
                'db_table': 'prodform',
            },
        ),
        migrations.CreateModel(
            name='PunchBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TabletSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='U1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='U2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('orderDate', models.CharField(blank=True, max_length=50, null=True)),
                ('orderNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('clientName', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('moc', models.CharField(blank=True, max_length=50, null=True)),
                ('toolType', models.CharField(blank=True, max_length=50, null=True)),
                ('shape', models.CharField(blank=True, max_length=50, null=True)),
                ('tabletSize', models.CharField(blank=True, max_length=50, null=True)),
                ('u1', models.CharField(blank=True, max_length=50, null=True)),
                ('u2', models.CharField(blank=True, max_length=50, null=True)),
                ('l1', models.CharField(blank=True, max_length=50, null=True)),
                ('l2', models.CharField(blank=True, max_length=50, null=True)),
                ('d', models.CharField(blank=True, max_length=10, null=True)),
                ('sett', models.CharField(blank=True, max_length=50, null=True)),
                ('platingType', models.CharField(blank=True, max_length=50, null=True)),
                ('rawMaterial', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('order_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('dwgNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('drgDate', models.CharField(blank=True, max_length=50, null=True)),
                ('approvalDate', models.CharField(blank=True, max_length=50, null=True)),
                ('master', models.CharField(blank=True, max_length=50, null=True)),
                ('masterOut', models.CharField(blank=True, max_length=50, null=True)),
                ('masterIn', models.CharField(blank=True, max_length=50, null=True)),
                ('punchBlankUsed', models.CharField(blank=True, max_length=10, null=True)),
                ('dieBlankUsed', models.CharField(blank=True, max_length=10, null=True)),
                ('hitDate', models.CharField(blank=True, max_length=50, null=True)),
                ('estimatedDelivery', models.CharField(blank=True, max_length=50, null=True)),
                ('planningOut', models.CharField(blank=True, max_length=50, null=True)),
                ('planningIn', models.CharField(blank=True, max_length=50, null=True)),
                ('blank', models.CharField(blank=True, max_length=10, null=True)),
                ('process', models.CharField(blank=True, max_length=10, null=True)),
                ('bodyTipMachining', models.CharField(blank=True, max_length=10, null=True)),
                ('headMachining', models.CharField(blank=True, max_length=10, null=True)),
                ('keywayTaperFinish', models.CharField(blank=True, max_length=10, null=True)),
                ('ht', models.CharField(blank=True, max_length=10, null=True)),
                ('grinding', models.CharField(blank=True, max_length=10, null=True)),
                ('hardChrome', models.CharField(blank=True, max_length=10, null=True)),
                ('qualityCheck', models.CharField(blank=True, max_length=10, null=True)),
                ('packingDispach', models.CharField(blank=True, max_length=10, null=True)),
                ('actualDelivery', models.CharField(blank=True, max_length=50, null=True)),
                ('dispachMode', models.CharField(blank=True, max_length=50, null=True)),
                ('couriesNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('new_orderDate', models.CharField(blank=True, max_length=50, null=True)),
                ('new_orderNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('new_clientName', models.CharField(blank=True, max_length=50, null=True)),
                ('new_value', models.CharField(blank=True, max_length=50, null=True)),
                ('new_moc', models.CharField(blank=True, max_length=50, null=True)),
                ('new_toolType', models.CharField(blank=True, max_length=50, null=True)),
                ('new_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('new_tabletSize', models.CharField(blank=True, max_length=50, null=True)),
                ('new_u1', models.CharField(blank=True, max_length=50, null=True)),
                ('new_u2', models.CharField(blank=True, max_length=50, null=True)),
                ('new_l1', models.CharField(blank=True, max_length=50, null=True)),
                ('new_l2', models.CharField(blank=True, max_length=50, null=True)),
                ('new_d', models.CharField(blank=True, max_length=10, null=True)),
                ('new_sett', models.CharField(blank=True, max_length=50, null=True)),
                ('new_platingType', models.CharField(blank=True, max_length=50, null=True)),
                ('new_rawMaterial', models.CharField(blank=True, max_length=50, null=True)),
                ('new_priority', models.CharField(blank=True, max_length=50, null=True)),
                ('new_order_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_dwgNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('new_drgDate', models.CharField(blank=True, max_length=50, null=True)),
                ('new_approvalDate', models.CharField(blank=True, max_length=50, null=True)),
                ('new_master', models.CharField(blank=True, max_length=50, null=True)),
                ('new_masterOut', models.CharField(blank=True, max_length=50, null=True)),
                ('new_masterIn', models.CharField(blank=True, max_length=50, null=True)),
                ('new_punchBlankUsed', models.CharField(blank=True, max_length=10, null=True)),
                ('new_dieBlankUsed', models.CharField(blank=True, max_length=10, null=True)),
                ('new_hitDate', models.CharField(blank=True, max_length=50, null=True)),
                ('new_estimatedDelivery', models.CharField(blank=True, max_length=50, null=True)),
                ('new_planningOut', models.CharField(blank=True, max_length=50, null=True)),
                ('new_planningIn', models.CharField(blank=True, max_length=50, null=True)),
                ('new_blank', models.CharField(blank=True, max_length=10, null=True)),
                ('new_process', models.CharField(blank=True, max_length=10, null=True)),
                ('new_bodyTipMachining', models.CharField(blank=True, max_length=10, null=True)),
                ('new_headMachining', models.CharField(blank=True, max_length=10, null=True)),
                ('new_keywayTaperFinish', models.CharField(blank=True, max_length=10, null=True)),
                ('new_ht', models.CharField(blank=True, max_length=10, null=True)),
                ('new_grinding', models.CharField(blank=True, max_length=10, null=True)),
                ('new_hardChrome', models.CharField(blank=True, max_length=10, null=True)),
                ('new_qualityCheck', models.CharField(blank=True, max_length=10, null=True)),
                ('new_packingDispach', models.CharField(blank=True, max_length=10, null=True)),
                ('new_actualDelivery', models.CharField(blank=True, max_length=50, null=True)),
                ('new_dispachMode', models.CharField(blank=True, max_length=50, null=True)),
                ('new_couriesNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('new_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('formid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='die_punch.productiondata')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userlog',
            },
        ),
        migrations.AddField(
            model_name='productiondata',
            name='punchBlankUsed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.punchblank'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='qualityCheck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.qualitycheck'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='rawMaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.rawmaterial'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.set'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.shape'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='tabletSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.tabletsize'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='toolType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.tooltype'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='u1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.u1'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='u2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.u2'),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('salary', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('networth', models.CharField(blank=True, max_length=10, null=True)),
                ('votercard', models.CharField(blank=True, max_length=20, null=True)),
                ('certificate', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'form',
            },
        ),
    ]
