# Generated by Django 4.0.1 on 2023-02-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('die_punch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='customerEmail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='customerMobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
