# Generated by Django 4.1.4 on 2023-02-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('die_punch', '0002_alter_customerdetail_customeremail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='blank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.blank'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='bodyTipMachining',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.bodytipmachining'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='clientName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.customerdetail'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.d'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='dieBlankUsed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.dieblank'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='dispachMode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.dispachmode'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='grinding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.grinding'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='hardChrome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.hardchrome'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='headMachining',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.headmachining'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='ht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.ht'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='keywayTaperFinish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.keywaytaperfinish'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='l1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.l1'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='l2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.l2'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='moc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.moc'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='packingDispach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.packingdispach'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='platingType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.platingtype'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.process'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='punchBlankUsed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.punchblank'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='qualityCheck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.qualitycheck'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='rawMaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.set'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.shape'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='tabletSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.tabletsize'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='toolType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.tooltype'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='u1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.u1'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='u2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='die_punch.u2'),
        ),
    ]
