# Generated by Django 4.0.1 on 2023-02-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('die_punch', '0003_alter_productiondata_blank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiondata',
            name='remark',
        ),
        migrations.AddField(
            model_name='productiondata',
            name='user_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='user_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='user_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='user_admin_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
