# Generated by Django 4.0.1 on 2023-02-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('die_punch', '0003_autoadddispatch_autoaddmain_autoaddmanufacturing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
